# Generated by Django 2.2.4 on 2019-08-09 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading_network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='district_list',
            field=models.ManyToManyField(blank=True, related_name='DistrictList', to='trading_network.District'),
        ),
        migrations.AddField(
            model_name='company',
            name='product_list',
            field=models.ManyToManyField(blank=True, related_name='ProductList', to='trading_network.Product'),
        ),
        migrations.AddField(
            model_name='company',
            name='trading_network',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='trading_network.TradingNetwork'),
            preserve_default=False,
        ),
    ]
