# Generated by Django 2.2.4 on 2019-08-12 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading_network', '0002_auto_20190809_1612'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Price',
            new_name='ProductList',
        ),
        migrations.RemoveField(
            model_name='company',
            name='product_list',
        ),
    ]
