# Generated by Django 2.2.4 on 2019-08-12 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading_network', '0003_auto_20190812_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_list', to='trading_network.Company'),
        ),
        migrations.AlterField(
            model_name='productlist',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices_list', to='trading_network.Product'),
        ),
    ]
